version: '3.7'

services:
  dotnet:
    container_name: dotnet
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./devcontainer.env
    volumes:
      -  './library-scripts:/tmp/library-scripts:rw'
      - '..:/workspace:cached'
    ports:
      - '5000:5000'
#      - '5001:5001'
    command: /bin/sh -c "while sleep 1000; do :; done"

  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}
    ports:
      - 27017:27017
    env_file:
      - ./devcontainer.env
    volumes:
      - ../.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ../.docker/mongodb/data/db/:/data/db/
      - ../.docker/mongodb/data/log/:/var/log/mongodb/
  mongoclient:
      image: mongoclient/mongoclient:latest
      environment:
        MONGOCLIENT_DEFAULT_CONNECTION_URL: "mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}"
      container_name: mongoclient
      hostname: mongoclient
      depends_on:
        - mongodb
      ports:
        - 3300:3000
